version: 2
jobs:
    build_py3:
        working_directory: ~/pytorch-transformers
        docker:
            - image: circleci/python:3.5
        steps:
            - checkout
            - run: sudo pip install --progress-bar off .
            - run: sudo pip install pytest codecov pytest-cov
            - run: sudo pip install spacy ftfy==4.4.3
            - run: sudo python -m spacy download en
            - run: python -m pytest -sv ./pytorch_transformers/tests/ --cov
            - run: codecov
        parallelism: 4
    build_py2:
        working_directory: ~/pytorch-transformers
        docker:
            - image: circleci/python:2.7
        steps:
            - checkout
            - run: sudo pip install --progress-bar off .
            - run: sudo pip install pytest codecov pytest-cov
            - run: sudo pip install spacy ftfy==4.4.3
            - run: sudo python -m spacy download en
            - run: python -m pytest -sv ./pytorch_transformers/tests/ --cov
            - run: codecov
        parallelism: 4
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_py3
      - build_py2